# Site settings
title: smile的博客
email: cjh_smile1987@163.com
description: > # this means to ignore newlines until "baseurl:"
  smile的博客
baseurl: "" # the subpath of your site, e.g. /blog/
# the base hostname & protocol for your site
url: "http://bodismile.github.io" 
rss_url: /pages/feed.xml

# Sidebar filter 使用category作为目录名
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

# Social account 设置社交账号
#twitter: username
# weibo:    ID
github: bodismile
# codepen:  username
# dribbble: username

#设置博客头像及小头像
avatar:  http://q.qlogo.cn/qqapp/100330589/0EC4E3116B80D1C5230054964793CBB8/100
favicon: http://qzapp.qlogo.cn/qzapp/100330589/0EC4E3116B80D1C5230054964793CBB8/30

# disqus 设置Disqus评论账号
disqus:
  shortname: bodismile

# google analytics 设置分析统计
#ga:
#  id: 
#  url: 

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
